## 1) Introduction of PyTorch Tensors and Basic Operations
### a) PyTorch tensors, initialization methods, and data types

In [11]:
import torch

# Tensor initialization
a = torch.tensor([1, 2, 3])                 # From list
b = torch.zeros((2, 3))                      # Zeros tensor
c = torch.ones((2, 3))                       # Ones tensor
d = torch.rand((2, 3))                       # Random values
e = torch.randn((2, 3))                      # Normal distribution

# Data types
f = torch.tensor([1, 2, 3], dtype=torch.float32)
g = torch.tensor([1, 2, 3], dtype=torch.int64)

print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)
print(d, d.dtype)
print(e, e.dtype)
print(f, f.dtype)
print(g, g.dtype)


tensor([1, 2, 3]) torch.int64
tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[0.7626, 0.3426, 0.9592],
        [0.1190, 0.2800, 0.5372]]) torch.float32
tensor([[ 0.2217, -2.5079,  1.7946],
        [ 0.3079,  1.1749,  0.0346]]) torch.float32
tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3]) torch.int64


### b) Tensor operations (arithmetic, broadcasting, indexing, reshaping)

In [2]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Arithmetic operations
print(x + y)
print(x * y)
print(x - y)
print(x / y)

# Broadcasting
z = torch.tensor([1, 2])
print(x + z)

# Indexing
print(x[0])
print(x[1, 1])

# Reshaping
reshaped = x.view(4)
print(reshaped)


tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[2, 4],
        [4, 6]])
tensor([1, 2])
tensor(4)
tensor([1, 2, 3, 4])


### c) Automatic differentiation using Autograd

In [3]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1

y.backward()
print("Gradient:", x.grad)


Gradient: tensor(7.)


### 2) Perform Linear Algebra Operations with TensorFlow

In [6]:
import tensorflow as tf

A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print(tf.add(A, B))
print(tf.matmul(A, B))
print(tf.transpose(A))

# Determinant
print(tf.linalg.det(A))

# Inverse
print(tf.linalg.inv(A))



tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


### 3) AND & OR Gates using Perceptron

In [7]:
import numpy as np

def perceptron(x, w, b):
    summation = np.dot(x, w) + b
    return 1 if summation >= 0 else 0

# Inputs
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

# AND Gate
weights_and = np.array([1, 1])
bias_and = -1.5

print("AND Gate")
for i in inputs:
    print(i, perceptron(i, weights_and, bias_and))

# OR Gate
weights_or = np.array([1, 1])
bias_or = -0.5

print("\nOR Gate")
for i in inputs:
    print(i, perceptron(i, weights_or, bias_or))


AND Gate
[0 0] 0
[0 1] 0
[1 0] 0
[1 1] 1

OR Gate
[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 1


### 4) XOR Problem using PyTorch Neural Network

In [8]:
import torch
import torch.nn as nn
import torch.optim as optim

# XOR dataset
X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
Y = torch.tensor([[0.], [1.], [1.], [0.]])

# Neural Network
class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

# Training
for epoch in range(1000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()

# Testing
print("XOR Output:")
print(model(X).round())


XOR Output:
tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


### 5) Simple Neural Network for Regression Problem

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim

# Sample regression data
X = torch.unsqueeze(torch.linspace(1, 10, 10), 1)
Y = 2 * X + 1

# Model
class RegressionNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = RegressionNet()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training
for epoch in range(1000):
    optimizer.zero_grad()
    prediction = model(X)
    loss = criterion(prediction, Y)
    loss.backward()
    optimizer.step()

# Prediction
print("Predicted:", model(torch.tensor([[5.0]])))


Predicted: tensor([[10.9957]], grad_fn=<AddmmBackward0>)
